django_project/music/music/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path('', views.homePage),
    path('about/', views.aboutPage),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/music/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('new-post/', views.post_new, name="new-post"),
    path('<slug:slug>', views.post_page, name="page"),
]

django_project/music/users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout')
]

django_project/music/posts/models.py
from django.db import models
from django.contrib.auth.models import User

#model class for Posts
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author= models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self) -> str:
        return self.title

django_project/music/users/models.py
from django.db import models

# Create your models here.

django_project/music/posts/forms.py
from django import forms
from . import models

class createPost(forms.ModelForm):
    class Meta:
        model=models.Post
        fields = ['title', 'body', 'banner', 'slug']
        

django_project/music/music/views.py
# from django.http import HttpResponse
from django.shortcuts import render


def homePage(req):
    return render(req, 'home.html')
    # return HttpResponse("Hello Django")

def aboutPage(req):
    return render(req, 'about.html')
    # return HttpResponse("About Page")

django_project/music/posts/views.py
from django.shortcuts import render, redirect

from .models import Post
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.

def posts_list(req):
    posts = Post.objects.all().order_by('-date')
    return render(req, 'posts/posts_list.html', {'posts': posts})

def post_page(req, slug):
    post = Post.objects.get(slug=slug)
    return render(req, 'posts/post_page.html', {'post': post})

@login_required(login_url="/users/login/")
def post_new(req):
    if req.method=='POST':
        form = forms.createPost(req.POST, req.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = req.user
            newpost.save()
            return redirect('posts:list')
    else:
        form =forms.createPost()
    return render(req, 'posts/post_new.html', {'form':form})

django_project/music/users/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth import login, logout

# Create your views here.
def registerUser(req):
    if req.method=="POST":
        form = UserCreationForm(req.POST)
        if form.is_valid():
            #form.save() also returns a user value
            login(req, form.save())
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(req, 'register_user.html', {"form":form})

def loginUser(req):
    if req.method=="POST":
        form = AuthenticationForm(data=req.POST)
        if form.is_valid():
            #login here
            login(req, form.get_user())
            if 'next' in req.POST:
                return redirect(req.POST.get('next'))
            return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(req, 'login.html', {"form":form})


def logoutUser(req):
    if req.method=="POST":
        logout(req)
        return redirect("posts:list")

django_project/music/posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
   New Post
{% endblock %}

{% block content %}
    <section>
        <h1>New Post</h1>
        <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %} 
            {{ form }}
            <button class="form-submit">Add Post</button>
        </form>
    </section>
{% endblock %}

django_project/music/posts/templates/posts/post_page.html
{% extends 'layout.html'%}

{% block  title%}
{{ post.title }}
{% endblock %}

{% block content %}
<section>
    <h1>{{ post.title }}</h1>
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p>
        <img 
            class="banner"
            src="{{ post.banner.url }}" 
            alt="{{ post.title }}"
        />
</section>
    
{% endblock %}

django_project/music/posts/templates/posts/posts_list.html
{% extends 'layout.html'%}

{% block  title%}
    Posts
{% endblock %}

{% block content %}
<section>
    <h1>Posts</h1>
    {% for post in posts %}
        <artcile class="post">
            <h2>
                <a href="{% url 'posts:page' slug=post.slug %}">
                {{ post.title }}
                </a>
            </h2>
            <p>{{ post.date }} by {{ post.author }}</p>
            <p>{{ post.body }}</p>
        </article>
    {% endfor %}
</section>
    
{% endblock %}


{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Posts List</title>
</head>
<body>
    <h1>Posts List</h1>
</body>
</html> {% endcomment %}

django_project/music/templates/about.html
{% extends 'layout.html'%}

{% block  title%}
About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.</p>
{% endblock content %}


{% comment %} <!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.</p>
</body>
</html> {% endcomment %}

django_project/music/templates/home.html
{% extends 'layout.html'%}

{% block  title%}
Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Check out my <a href="/about">About</a> page.</p>
{% endblock content %}


{% comment %} <!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <h1>Home</h1>
    <p>Check out my <a href="/about">About</a> page.</p>
</body>
</html> {% endcomment %}

django_project/music/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Web App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/">
            <span role="img" aria-label="Home" title="Home">🏠</span>
        </a> | 
        <a href="/about">
            <span role="img" aria-label="About" title="About">😀</span>
        </a> | 
        <a href="{% url 'posts:list' %}">
            <span role="img" aria-label="Posts" title="Posts">📰</span>
        </a> | 
        {% if user.is_authenticated %}
            <a href="{% url 'posts:new-post' %}">
                <span role="img" aria-label="New Post" title="New Post">🆕</span>
            </a> | 
            <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %} 
                <button class="logout-button" aria-label="User Logout" title="User Logout">👋</button>
            </form>
        {% else %}
            <a href="{% url 'users:register' %}">
                <span role="img" aria-label="User Registration" title="User Registration">🚀</span>
            </a> | 
            <a href="{% url 'users:login' %}">
                <span role="img" aria-label="User Login" title="User Login">🔏</span>
            </a>
        {% endif %}
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

django_project/music/users/templates/login.html
{% extends 'layout.html' %}

{% block title %}
    User Login
{% endblock %}

{% block content %}
    <h1>User Login</h1>
    <form class="form-with-validation" action="/users/login/" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}" />
        {% endif %}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}

django_project/music/users/templates/register_user.html
{% extends 'layout.html'%}

{% block  title%}
Register User
{% endblock %}

{% block content %}
<section>
    <h1>Register New User</h1>
   <form action="/users/register/" method="post" class="form-with-validation">
    {% csrf_token %}
    {{ form }}
    <button class="form-submit">Submit</button>
    </form>
</section>
    
{% endblock %}